"""initial schema

Revision ID: aa2a9715d340
Revises: 
Create Date: 2026-03-26 03:18:36.406265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2a9715d340'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('sha1', sa.String(length=40), nullable=False),
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('parent_sha256', sa.String(length=64), nullable=True),
    sa.Column('child_artifacts', sa.JSON(), nullable=False),
    sa.Column('strings', sa.JSON(), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('functions', sa.JSON(), nullable=False),
    sa.Column('behavior', sa.JSON(), nullable=False),
    sa.Column('tool_runs', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('baseline_diff', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('chunk_hashes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('sha256')
    )
    op.create_table('baselines',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('product', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('signer', sa.String(length=256), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('chunk_hashes', sa.JSON(), nullable=False),
    sa.Column('function_hashes', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('root_sha256', sa.String(length=64), nullable=False),
    sa.Column('artifact_shas', sa.JSON(), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('claimed_product', sa.String(length=256), nullable=True),
    sa.Column('claimed_signer', sa.String(length=256), nullable=True),
    sa.Column('verdict_state', sa.String(length=32), nullable=False),
    sa.Column('verdict_summary', sa.Text(), nullable=False),
    sa.Column('pending_actions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verdicts',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('functions', sa.JSON(), nullable=False),
    sa.Column('behavior', sa.JSON(), nullable=False),
    sa.Column('pending_actions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('sha256')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verdicts')
    op.drop_table('submissions')
    op.drop_table('baselines')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
